version: '3.8'

services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    networks:
      - jenkins
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "2376:2376"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  my-jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-jenkins
    restart: unless-stopped
    networks:
      - jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      DOCKER_HOST: tcp://jenkins-docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  jenkins-docker-certs:
  jenkins-data:

networks:
  jenkins:
